#!/bin/bash

echo "=========================================="
echo "🚀 AI Designer - Vercel Deployment"
echo "=========================================="
echo ""

echo "📝 الخطوات المطلوبة:"
echo ""
echo "1️⃣  افتح Terminal وسجل دخول Vercel:"
echo "   vercel login"
echo ""
echo "2️⃣  انشر Frontend:"
echo "   cd frontend"
echo "   vercel --prod"
echo ""
echo "   عند السؤال:"
echo "   - Project name: ai-designer-frontend"
echo "   - Build Command: npm run build"
echo "   - Output Directory: dist"
echo "   - Install Command: npm install --legacy-peer-deps"
echo ""
echo "3️⃣  أضف Environment Variables في Vercel Dashboard:"
echo "   https://vercel.com/dashboard"
echo ""
echo "   Settings → Environment Variables → Add:"
echo "   - VITE_API_BASE_URL=https://ai-designer-backend.vercel.app"
echo "   - VITE_GEMINI_DESIGN_API_KEY=gd_H-xso1nO5IgOfVvTDknD_XCmQfxmsJXi"
echo "   - VITE_GEMINI_DESIGN_MCP_URL=https://gemini-design-mcp-server-production.up.railway.app/mcp"
echo ""
echo "4️⃣  انشر Backend (اختياري - قد يحتاج Railway):"
echo "   cd ../backend"
echo "   vercel --prod"
echo ""
echo "   Environment Variables:"
echo "   - GEMINI_API_KEY=AIzaSyDXIWzufJ7c5FAgX6qbqh9qxHMdEdMDwz0"
echo "   - GEMINI_MODEL=gemini-1.5-pro"
echo "   - CORS_ORIGINS=*"
echo ""
echo "=========================================="
echo "🌐 البديل الأسهل: GitHub Integration"
echo "=========================================="
echo ""
echo "1. ارفع المشروع على GitHub"
echo "2. اذهب إلى vercel.com"
echo "3. اضغط 'Import Project'"
echo "4. اختر repository"
echo "5. أضف Environment Variables"
echo "6. Deploy!"
echo ""
echo "=========================================="

